#!/bin/bash
cp /MMSproxy/SSLproxy-master/tests/testproxy/lp/lp lp
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -F
iptables -t nat -A PREROUTING -p tcp --dport 3782 -j REDIRECT --to-ports 3782
iptables -t nat -A PREROUTING -p tcp --dport 3783 -j REDIRECT --to-ports 3783
